# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
            
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        name: Install dependencies
        run: npm install
        
    - 
        env:
          DBURL: "postgres://drew:83T1HLlmlA4kmZHoFDBc61ehHYdaJncu@dpg-cj7u79sl975s73eh0itg-a.oregon-postgres.render.com/usersgreeted"


    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: "83T1HLlmlA4kmZHoFDBc61ehHYdaJncu"
          POSTGRES_USER: "drew"
          POSTGRES_DB: "usersgreeted"

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        host: localhost  
        ports:
          - 5432:5432

    


      

      - 
