name: Running Tests

on: [push]

jobs:
  Test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres

        env:
          POSTGRES_PASSWORD: 83T1HLlmlA4kmZHoFDBc61ehHYdaJncu
          POSTGRES_USER: drew
          POSTGRES_DB: usersgreeted

        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      # run steps required in the workflow
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install dependencies
        run: npm install

      - name: migrate database
        run: node migrate.js
        env:
          DBURL: "postgres://drew:83T1HLlmlA4kmZHoFDBc61ehHYdaJncu@dpg-cj7u79sl975s73eh0itg-a.oregon-postgres.render.com/usersgreeted"

      - name: Run the mock tests function
        run: npm test
        env:
          DBURL: postgres://drew:83T1HLlmlA4kmZHoFDBc61ehHYdaJncu@dpg-cj7u79sl975s73eh0itg-a.oregon-postgres.render.com/usersgreeted


